version: '3'
 
services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=Asia/Seoul
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/cache:/var/cache/bind
      - ./bind9/records:/var/lib/bind
    restart: unless-stopped

  traefix:
    image: traefik:v3.0
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web" 

  clamav:
    image: clamav/clamav:stable
    container_name: "clamav"
    volumes:
      - source:clam_db, target=/var/lib/clamav