version: '3'
 
services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=Asia/Seoul
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind9/config:/etc/bind
      - ./bind9/cache:/var/cache/bind
      - ./bind9/records:/var/lib/bind
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports: 
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - api
      - db

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
     - ./certbot/conf:/etc/letsencrypt
     - ./certbot/www:/var/www/certbot
     - ./certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

nfs-providing:

fedora-desktop:
  container_name: fedora-desktop
  image: kasmweb/fedora-39-desktop:1.15.0-rolling
  restart: always
  ports:
    6901:6901
  enviroment:
    VNC_PW=encryption-vault
    


networks:
  public-zone:
    name: public-zone-management

volumes:
  nfs-set:
    driver-opts:
      type: "nfs"
      o: "ipaddr=nas.elastichomelab.com"
      #device: "/mnt/storage/tls:/"